### ISSUE TITLE
About page GitHub URL out of date

### ISSUE THREAD

**Issue by edmorley** [h4writer/arewefastyet#104]
The about page lists the GitHub URL as 'https://github.com/haytjes/arewefastyet' rather than 'https://github.com/h4writer/arewefastyet':
https://github.com/h4writer/arewefastyet/blob/6604e22af67274e76cb26cba4272f7e1a957a879/website/index.html#L147

Not exactly urgent, since the old URL does redirect, but thought it worth mentioning :-)

**Comment by h4writer** [comment]
Right, fixed it:
https://github.com/h4writer/arewefastyet/commit/b5bb95ea75c08929ebf064cd4cc5a854ce7009d5
