### ISSUE TITLE
Run backtracking on windows and flame

### ISSUE THREAD

**Issue by h4writer** [h4writer/arewefastyet#44]

**Comment by h4writer** [comment]
Revisions:
d56b3ddc24d8bb4e40f47914a13c911de2a1fbd1
1b42e2660397e7b23cc70c8659845d9c45f650e0
6eb1d8306afc94b2d5f926b37a749672b8865020

**Comment by flynnsky** [comment]
Revisions:
d56b3dd
1b42e26
6eb1d83
