### ISSUE TITLE
update fbirds benchmark to use load and store

### ISSUE THREAD

**Issue by sunfishcode** [h4writer/arewefastyet#48]
Now that we have a proper load and store, the asmjs-ubench fbirds test can be more interesting. See the update to the fbirds testcase here for the code:

https://hg.mozilla.org/integration/mozilla-inbound/rev/f47810257e98

**Comment by bnjbvr** [comment]
Hehe, beat you to it https://github.com/h4writer/arewefastyet/pull/46

**Comment by h4writer** [comment]
Closing since already fixed ;)
