### ISSUE TITLE
Make it possible to send description/comment with a benchmark

### ISSUE THREAD

**Issue by h4writer** [h4writer/arewefastyet#50]
Currently a benchmark will report its name and version number. It would be good to also make it possible to send some sort of description.

Adding the version number was done in dc5db9b277f3589a3012724ebd1968e962cf6b73. That can be used as a base.

This feature is for 'shumway', but can be used by other benchmarks. The shumway benchmark will pull the newest swf to js compiler when run. Upon sending results we want to send the "shumway version" in the description.

Fully completed this should:
1) Update driver/benchmark.py being able to set a description
2) Update driver/submitter.py to send a description
3) Update database/schema.sql to have a place to save the description
4) Update website/UPDATE.php to get the description and save it in the database
5) Update the website/* + server/* to use this description.

But this can be done in parts. Every point can be done one at a time and get committed already.

**Comment by h4writer** [comment]
Note: The different parts start easy like (1) and (2) and become more difficult towards the end, like (5). So this is a good bug to start easy and get to know more and more about the system. Towards the end you will have a good understanding of the entire mechanism.

**Comment by sushant94** [comment]
Hey,
I'm starting this today. You can assign this to me :)

**Comment by h4writer** [comment]
Awesome,
I think I need to give you commit rights before I can assign or something. Though I would prefer the fork + pull request route. (Since that gives me an review opportunity).
So though I cannot assign you in github, but you are assigned ;).

**Comment by sushant94** [comment]
Posting initial work to check if I'm on the right track: [commit ab0162e8] (https://github.com/sushant94/arewefastyet/commit/ab0162e82097ceb06355cbae3d29487568648362)

I'm not sure which table to add description to, I need some advice here.
Also, I went through UPDATE.php and I'm not sure what I need to change there to allow for description to be posted along with the other details.

And is there a way to test my changes without  having to clone all the js shells?

**Comment by h4writer** [comment]
1) The commit looks already quite good. Though I would recommend to make self.description in Benchmark empty by default and just add a "setDescription" method to set the description if needed (instead of using the constructor to set the description).

2) The table is indeed an interesting question. I didn't think you would proceed that fast, so thought I had some extra time before thinking about it ;).
![db](https://cloud.githubusercontent.com/assets/573482/6347785/df35fe16-bc1a-11e4-830b-06c385e22612.png)
This is a layout of the db before and how I think it should look. The blocks are table names, underneath the fields. The arrows indicate it has an ID pointing to that table. So the big change will be to move the dependency of awfy_breakdown from awfy_build to awfy_score. This means a lot of queries will need to get adjusted. So please search through the whole directory to fix all these. Secondly: bonuspoints if you write a migrate tool ;)

3) Adjusting https://github.com/h4writer/arewefastyet/blob/master/driver/dostuff.py#L37 to only have mozilla should enable you to only run the inbound js shell ;)

**Comment by h4writer** [comment]
Phase 1:
https://github.com/h4writer/arewefastyet/commit/8bb83dff4ed027bb3607f85338bce39b0f60d7bc
https://github.com/h4writer/arewefastyet/commit/bd9fcc44142a0d73bf9fcbcc5714048abafd77c9
https://github.com/h4writer/arewefastyet/commit/bd9fcc44142a0d73bf9fcbcc5714048abafd77c9

Add link from awfy_breakdown to awfy_score. Not yet removing the link to awfy_build. First all slaves need to get on the newest submitter.

**Comment by h4writer** [comment]
ce74d1bfe5f6b8fb0080fc63ad9674cf1b047124
06ea5785d7ee245c8380defea13d9138afd2918f
34e62646c59ca2ce94a70f965284be6077726372
2e8dc0ee4ce674ab59f582ac1602138e1aba1a43
7a5ac329ae6d48741ee29705b23e7140b19880d6
709bf9c613c890db9cc47ba357531e6ca8bf1cff
