### ISSUE TITLE
Why do the Octane scores for V8-Turbofan on this website seemingly contradict Google's numbers so strongly?

### ISSUE THREAD

**Issue by Ajedi32** [h4writer/arewefastyet#75]
Just today, Google released [a blog post](https://blog.chromium.org/2015/07/revving-up-javascript-performance-with.html) discussing TurboFan. In it, they claimed a 29% increase on the zlib score of the Octane benchmark with TurboFan enabled.

Looking at [the Octane zlib scores for V8-Turbofan on arewefastyet](http://arewefastyet.com/#machine=28&view=single&suite=octane&subtest=zlib), it seems the opposite is true. V8-Turbofan has a significantly _lower_ score for the Octane zlib tests than V8 does. Any idea why this is? Seems kind of odd that Turbofan is seemingly way slower than all other engines [in every benchmark](http://arewefastyet.com/) on arewefast yet, while at the same time Google is claiming significant improvements over V8 with TurboFan off.

Is Google simply wrong here? Or could this be an indication of some sort of problem with arewefastyet's appraisal of TurboFan's performance?

**Comment by bmeurer** [comment]
arewefastyet is probably a bit misleading here, since the V8 graph actually shows TurboFan numbers in case of asm.js (zlib is asm.js), while V8-TurboFan graph shows numbers for TurboFan enabled for all of JavaScript, which is not properly optimized yet (that's why we don't ship TurboFan for everything yet).

**Comment by h4writer** [comment]
Oh no, google is right in claiming turbofan gave them a big improvement on zlib. The catch is they only enabled it by default for asm.js code. Their real performance with turbofan enabled on asm.is code is the dark green line. The turbofan line is still experimental. They want to enable turbofan on all code. That is what the light green line shows. Their current performance with turbofan enabled for all scripts isn't good yet. Also the reason they didn't make that the default configuration yet.h4writer/arewefastyet wrote:Just today, Google released a blog post discussing TurboFan. In it, they claimed a 29% increase on the zlib score of the Octane benchmark with TurboFan enabled.

Looking at the Octane zlib scores for V8-Turbofan on arewefastyet, it seems the opposite is true. V8-Turbofan has a significantly lower score for V8-TurboFan than it does for V8. Any idea why this is? Seems kind of odd that Turbofan is seemingly way slower than all other engines in every benchmark on arewefast yet, while at the same time Google is claiming significant improvements over V8 with TurboFan off.

Is Google simply wrong here? Or could this be an indication of some sort of problem with arewefastyet's appraisal of TurboFan's performance?

**Comment by titzer** [comment]
h4writer and bmeurer are correct here. AWFY is testing a non-production configuration of TurboFan. So the "normal" Chrome line is actually showing TurboFan performance. To disable TurboFan for asm.js, you can pass --noturbo-asm and reproduce the results in the blog post.

**Comment by titzer** [comment]
Also, as pointed out in the blog post, we've started to enable TurboFan for select JavaScript features other than asm.js in Beta 45.

**Comment by Ajedi32** [comment]
Ah, okay. So V8 is "V8 with TuboFan enabled", while V8-Turbofan is "V8 with CrankShaft disabled and TurboFan used exclusively for everything". Makes sense.

And given that the blog post says:

> Over the coming months, we expect to enable TurboFan for more and more types of JavaScript, with the eventual goal of entirely replacing our existing CrankShaft compiler.

Presumably we should start seeing the V8-Crankshaft performance converge with V8 over time, until both engines are identical, right? Got it.
