### ISSUE TITLE
Mismatch in path to results file.

### ISSUE THREAD

**Issue by dhananjay92** [h4writer/arewefastyet#83]
For benchmarks like Dromaeo, results are stored in `puppet/results` at [server.py#L51](https://github.com/h4writer/arewefastyet/blob/master/slave/server.py#L51). But the BrowserExecutor waits for results on just `results` file at [executors.py#L49](https://github.com/h4writer/arewefastyet/blob/master/slave/executors.py#L49). This causes the executor to wait indefinitely.
Does this need fixing? Or am I just missing some context here?

**Comment by h4writer** [comment]
Yeah. Throughout the rewrite I named the directory "puppet" and only very late I decided to rename to "slave". As a result this path wasn't updated yet. Good find!
