### ISSUE TITLE
Updated Db Schema and/or UPDATE.php

### ISSUE THREAD

**Issue by dhananjay92** [h4writer/arewefastyet#86]
I think either the copy of UPDATE.php Or schema on this repo is an old one. On my local setup, when submitter.py tries to submit results to UPDATE.php, I get following error.
```
ERROR: Unknown column 'extra_info' in 'field list'
```
It's originating from [`UPDATE.php`](https://github.com/h4writer/arewefastyet/blob/master/website/UPDATE.php#L99). Because [`awfy_score`](https://github.com/h4writer/arewefastyet/blob/master/database/schema.sql#L233) doesn't have any column named `extra_info`. 
Can you please update whichever needs updating?

**Comment by h4writer** [comment]
Sorry I always forget to update the schema.sql file:
129c8ead357277fff1aea3efa85f175e54499a7c

**Comment by dhananjay92** [comment]
Great. Thanks. :smile:

**Comment by h4writer** [comment]
I just pushed a commit that will make it easier for me to deploy changes to the database.
I've added a rudimentary 'migration' system. In the future if I change the database structure I will do this incremental to the current database layout and push a script to transform existing data to the newest layout.

I'll change a small thing in the future. Therefore this is good to have in place now ;).
